In [1]:
import tensorflow as tf
session = tf.Session()

### operaciones aritmeticas

In [2]:
x = 3
y = 4

In [3]:
print(session.run(tf.add(x,y))) ## se realiza la suma de x con y

7


In [4]:
print(session.run(tf.subtract(x,y))) ## se realiza la resta de x con y

-1


In [5]:
print(session.run(tf.multiply(x,y))) ## se realiza la multiplicacion de x con y

12


In [6]:
print(session.run(tf.truediv(x,y))) ## realiza la division de 3 dividido 4

0.75


In [7]:
print(session.run(tf.mod(23.0, 5.0))) ## realiza la division de 23 dividido 5, mostrando solo el resto de la division (lo que se conoce como el "modulo")

3.0


In [8]:
v1 = [1.0, 0., 0.] ## vector v1
v2 = [0., 1., 0.] ## vector v2
v3 = tf.cross(v1,v2) ## realiza el producto cruz del vector "v1" y "v2" y el resultado es igual al vector "v3"
print(session.run(v3)) 


[0. 0. 1.]


### funciones matematicas

In [9]:
x = [-3.,-2.,-1.,0.,1.,2.]

In [11]:
print(session.run(tf.abs(x))) ##saca el valor absoluto

[3. 2. 1. 0. 1. 2.]


In [12]:
print(session.run(tf.ceil(6.4))) ##redondeo a la alta

7.0


In [13]:
print(session.run(tf.floor(6.4))) ##redondeo a la baja

6.0


In [15]:
print(session.run(tf.round(6.4))) ##redondeo clasico.

6.0


In [16]:
print(session.run(tf.sin(x))) ##funcion seno

[-0.14112    -0.9092974  -0.84147096  0.          0.84147096  0.9092974 ]


In [18]:
print(session.run(tf.cos(x))) ##funcion coseno

[-0.9899925  -0.4161468   0.5403023   1.          0.5403023  -0.41614684]


In [21]:
print(session.run(tf.tan(x))) ##funcion tangente

[ 0.14254653  2.18504    -1.5574079   0.          1.5574077  -2.1850398 ]


In [23]:
print(session.run(tf.log(x))) ##funcion logaritmo

[      nan       nan       nan      -inf 0.        0.6931472]


In [24]:
x = [-3.,-2.,-1.,0.,1.,2.]
y = [4.,3.,7.,-4.,-3.,7.]

In [26]:
print(session.run(tf.maximum(x,y))) ##compara los 2 vectores y devuelve el maximo valor de cada comparacion

[4. 3. 7. 0. 1. 7.]


In [28]:
print(session.run(tf.minimum(x,y))) ##compara los 2 vectores y devuelve el minimo valor de cada comparacion

[-3. -2. -1. -4. -3.  2.]


In [30]:
print(session.run(tf.negative(x))) ##lo que era positivo lo transforma en negativo y viceversa

[ 3.  2.  1. -0. -1. -2.]


In [43]:
print(session.run(tf.square(x))) ##eleva al cuadrado el tensor "x"

[9. 4. 1. 0. 1. 4.]


In [41]:
print(session.run(tf.pow(x,4))) ##eleva a la cuarta el tensor "x", tener en cuenta que se puede elevar a la potencia que queramos.

[81. 16.  1.  0.  1. 16.]


In [34]:
print(session.run(tf.sqrt(x))) ##raiz cuadrado del tensor "x"

[      nan       nan       nan 0.        1.        1.4142135]


In [35]:
print(session.run(tf.rsqrt(x))) ##la inversa de la raiz cuadrada; osea "1/sqrt(x)"

[       nan        nan        nan        inf 1.         0.70710677]


In [44]:
print(session.run(tf.sign(x))) ##devuelve "-1" si el valor del tensor es negativo, "0" si el valor es cero, y "1" si el valor es positivo

[-1. -1. -1.  0.  1.  1.]


In [46]:
print(session.run(tf.squared_difference(x,y))) ##suma de los cuadrados de las diferencias de los tensores "x" e "y"

[49. 25. 64. 16. 16. 25.]


### funciones propias

#### ejemplo: y = 5x**2 - 7x + 15

In [52]:
def mi_funcion(value):
    y = tf.subtract(5*tf.square(value), 7*value) + 15
    return(y)

In [53]:
print(session.run(mi_funcion(5)))

105
