In [2]:
import tensorflow as tf
session = tf.Session()

# 1. como crear matrices

In [36]:
identity = tf.diag([1.,1.,1.,1.]) ##crea la matriz identidad con una diagonal de 4 unos 
print(session.run(identity)) ## imprime la matriz identidad

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
A = tf.random_normal([3,4]) ##crea una matriz con una distribucion normal de 3 filas y 4 columnas
print(session.run(A))

[[-0.13810882  0.7397819  -1.1417274  -1.2173609 ]
 [-1.2684287   2.9143138   0.56612486  0.09804371]
 [-2.650426    2.0227664   0.5364391   0.3698414 ]]


In [25]:
B = tf.fill([3,4], 1991.) ##crea una matriz "fill" de 3 filas y 4 columnas, rellenada con el valor "1991"
print(session.run(B))

[[1991. 1991. 1991. 1991.]
 [1991. 1991. 1991. 1991.]
 [1991. 1991. 1991. 1991.]]


In [22]:
C = tf.random_uniform([4,3]) ##crea una matriz con distribucion aleatoria uniforme de 4 filas y 3 columnas
print(session.run(C))

[[0.84451103 0.8700391  0.33765447]
 [0.56964386 0.9341855  0.59106266]
 [0.3102361  0.9817889  0.196239  ]
 [0.19754755 0.9594486  0.99720573]]


In [23]:
import numpy as np
data = np.array([ [1.,2.,3.],[4.,5.,6.],[7.,8.,9.] ]) ##crea una matriz de numpy
D = tf.convert_to_tensor(data) ##se convierte la matriz de numpy en un tensor de tensorflow
print(session.run(D))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 2. operaciones con matrices

In [27]:
print(session.run(A+B)) ##suma la matriz A con la matriz B

[[1992.063  1990.2958 1991.2207 1992.9891]
 [1991.5721 1992.5923 1991.2018 1990.969 ]
 [1990.5602 1991.8689 1991.3848 1991.6624]]


In [29]:
print(session.run(B-B)) ##resta la matriz B con la matriz B

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
print(session.run(tf.matmul(A,C))) ##multiplica la matriz A con la matriz C

[[-1.6617342  -2.047317   -1.0205361 ]
 [-1.1777287   0.44738185 -1.1480614 ]
 [-1.0361184  -0.15641531 -0.7824133 ]]


In [38]:
print(session.run(tf.matmul(A, identity))) ##multiplica la matriz A con la matriz identity

[[ 2.1847703  -0.1730342  -0.08577558  2.0844495 ]
 [-0.10634559 -1.0791316  -0.21703455 -1.1177057 ]
 [ 1.0762947   0.087026   -0.25548673 -0.19954063]]


# 3. Transpuesta, determinante, inversa

In [40]:
print(session.run(tf.transpose(D))) ## crea la transpuesta de la matriz D

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [43]:
print(session.run(tf.matrix_determinant(D))) ## saca el determinante de D

6.66133814775094e-16


In [46]:
print(session.run(tf.matrix_inverse(D))) ## saca la inversa de la matriz D

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


## 5. valores y vectores propios

In [51]:
print(session.run(tf.self_adjoint_eigvals(D))) ##valores propios para la matriz D

[-3.15746784 -0.67276795 18.8302358 ]


In [52]:
print(session.run(tf.self_adjoint_eig(D))) ## el primer array corresponde a los valores propios y los arrays restantes son cada uno de los vectores propios correspondiente a cada valor propio

(array([-3.15746784, -0.67276795, 18.8302358 ]), array([[-0.80238891, -0.43402538,  0.40962667],
       [-0.16812656,  0.82296167,  0.54264865],
       [ 0.57263033, -0.36654613,  0.73330651]]))
